package com.sss.data.entity;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
/**
 * Commentable Entity class
 * @author vaivorom
 *
 */
@Entity
public class Commentable {
	/**
	 * Member that stores id. 
	 * Value generated by Spring Framework.
	 */
	@Id @GeneratedValue
	private Long id;
	/**
	 * getter for id
	 * @return
	 */
	public Long getId() {
		return id;
	}
	/**
	 * fluent setter for id
	 * @param id
	 * @return
	 */
	public Commentable setId(Long id) {
		this.id = id;
		return this;
	}
}
