package com.sss.data.entity;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * Task Entity class
 * @author vaivorom
 *
 */
@Entity
public class Task {
	/**
	 * Member that stores id. 
	 * Value generated by Spring Framework.
	 */
	@Id
	@GeneratedValue
	private Long id;
	/**
	 * Member that stores an task's title.
	 */
	private String title;
	/**
	 * Member that stores a list of questions that task contains.
	 */
	@ManyToMany
	private List<Question> questions;
	/**
	 * fluent setter for questions
	 * @param questions
	 * @return
	 */
	public Task setQuestions(List<Question> questions) {
		this.questions = questions;
		return this;
	}
	/**
	 * fluent setter for title
	 * @param title
	 * @return
	 */
	public Task setTitle(String title) {
		this.title = title;
		return this;
	}
	/**
	 * getter for title
	 * @return
	 */
	public String getTitle() {
		return this.title;
	}
	/**
	 * getter for questions
	 * @return
	 */
	public List<Question> getQuestions() {
		return this.questions;
	}
	/**
	 * fluent setter for id
	 * @param id
	 * @return
	 */
	public Task setId(Long id) {
		this.id = id;
		return this;
	}
	/**
	 * getter for id
	 * @return
	 */
	public Long getId() {
		return this.id;
	}
}
